# Generated by Django 3.1a1 on 2020-05-31 18:28

import django.db.models.deletion
from django.db import migrations, models

import core.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VirtualDomain",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="name"),
                ),
                (
                    "dkim_key_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="dkim key name"
                    ),
                ),
                ("dkim_key", models.TextField(blank=True, verbose_name="dkim key")),
                (
                    "dkim_status",
                    models.IntegerField(
                        choices=[
                            (0, "not set"),
                            (1, "dns record not found"),
                            (2, "no dns key found in record"),
                            (3, "key and dns record don't match"),
                            (4, "ok"),
                        ],
                        default=0,
                        verbose_name="dkim status",
                    ),
                ),
                (
                    "dkim_last_update",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="dkim status last update"
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="display name"
                    ),
                ),
                (
                    "short_display_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="short display name"
                    ),
                ),
                (
                    "imap_address",
                    models.URLField(blank=True, verbose_name="imap address"),
                ),
                (
                    "pop_address",
                    models.URLField(blank=True, verbose_name="pop address"),
                ),
                (
                    "smtp_address",
                    models.URLField(blank=True, verbose_name="smtp address"),
                ),
            ],
            options={"verbose_name": "domain", "verbose_name_plural": "domains",},
        ),
        migrations.CreateModel(
            name="VirtualUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email"
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        default=core.utils.random_password,
                        max_length=300,
                        verbose_name="password",
                    ),
                ),
                (
                    "quota",
                    models.BigIntegerField(default=0, null=True, verbose_name="quota"),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.virtualdomain",
                        verbose_name="domain",
                    ),
                ),
            ],
            options={"verbose_name": "user", "verbose_name_plural": "users",},
        ),
        migrations.CreateModel(
            name="VirtualAlias",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.EmailField(max_length=254, verbose_name="source")),
                (
                    "destination",
                    models.EmailField(max_length=254, verbose_name="destination"),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.virtualdomain",
                        verbose_name="domain",
                    ),
                ),
            ],
            options={"verbose_name": "alias", "verbose_name_plural": "aliases",},
        ),
    ]
