# Generated by Django 3.1a1 on 2020-06-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="virtualdomain",
            name="imap_address",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="imap address"
            ),
        ),
        migrations.AlterField(
            model_name="virtualdomain",
            name="pop_address",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="pop address"
            ),
        ),
        migrations.AlterField(
            model_name="virtualdomain",
            name="smtp_address",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="smtp address"
            ),
        ),
    ]
