# Generated by Django 3.0.7 on 2020-06-16 09:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20200604_1836"),
    ]

    operations = [
        migrations.AddField(
            model_name="virtualdomain",
            name="dmarc_last_update",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="dmarc status last update",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="virtualdomain",
            name="dmarc_status",
            field=models.IntegerField(
                choices=[
                    (0, "No DNS record for DMARC"),
                    (1, "DNS record does not contain v=DMARC1"),
                    (2, "ok"),
                ],
                default=0,
                verbose_name="dmarc status",
            ),
        ),
    ]
