# Generated by Django 3.0.7 on 2020-06-16 10:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_auto_20200616_1132"),
    ]

    operations = [
        migrations.AddField(
            model_name="virtualdomain",
            name="spf_last_update",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="spf status last update",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="virtualdomain",
            name="spf_status",
            field=models.IntegerField(
                choices=[(0, "No DNS record for SPF"), (1, "ok")],
                default=0,
                verbose_name="spf status",
            ),
        ),
    ]
